'use strict';
(() => {
 const C=window.COURSE, KEY='hrc.billing-foundations.v1', TIME_KEY=KEY+'.time';
 const $=(s,root=document)=>root.querySelector(s), $$=(s,root=document)=>[...root.querySelectorAll(s)];
 const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const titleText=v=>String(v??'').replace(/\b[\p{L}\p{N}][\p{L}\p{N}'’-]*/gu,w=>/^[A-Z0-9&/-]+$/.test(w)?w:w.charAt(0).toUpperCase()+w.slice(1));
 const defaults=()=>({version:1,route:'welcome',modules:{},exam:{answers:[],attempts:[],index:0},name:'',collapsed:null});
 let storageOK=true, state=defaults(), elapsed=0, selectedToken=null, selectedLeft=null, feedback={};
 function warn(message){const el=$('#storageWarning');el.hidden=false;el.textContent=message;}
 try {const raw=localStorage.getItem(KEY);if(raw){const parsed=JSON.parse(raw);if(parsed.version!==1||!parsed.modules||typeof parsed.modules!=='object'||!parsed.exam||!Array.isArray(parsed.exam.answers)||!Array.isArray(parsed.exam.attempts))throw Error('Invalid saved data');state={...defaults(),...parsed};}elapsed=Math.max(0,Number(localStorage.getItem(TIME_KEY))||0);localStorage.setItem(KEY,JSON.stringify(state));}
 catch(e){storageOK=false;warn('Browser saving is unavailable or saved data could not be read. You can learn in this session, but export your answers before leaving.');}
 const save=()=>{if(!storageOK)return;try{localStorage.setItem(KEY,JSON.stringify(state));}catch(e){storageOK=false;warn('Your browser could not save this change. Export your answers before leaving this page.');}};
 function ms(id){if(!state.modules[id])state.modules[id]={read:false,activity:{},cfu:{answers:[],attempts:[]},reflection:{text:'',submitted:false}};return state.modules[id];}
 function as(m){const a=ms(m.id).activity;if(m.activity.type==='sequence'&&!a.order)a.order=[3,0,5,1,4,2];if(m.activity.type==='forms'){a.forms??={};C.forms.forEach(f=>{a.forms[f.id]??={index:0,history:[],done:false};if(a.forms[f.id].awaiting&&!a.forms[f.id].answer)a.forms[f.id].awaiting=false;});a.tab??='cms';}return a;}
 C.modules.forEach(m=>{ms(m.id);as(m);});
 const reflectionDone=m=>{const r=ms(m.id).reflection;return r.submitted&&r.text.trim().length>=20;};
 const activityDone=m=>{const a=as(m);return !!a.done&&(!m.activity.explanation||!!a.explanationSubmitted);};
 const cfuDone=m=>ms(m.id).cfu.attempts.some(a=>a.score===m.cfu.length);
 const steps=m=>[ms(m.id).read,activityDone(m),cfuDone(m),reflectionDone(m)];
 const complete=m=>steps(m).every(Boolean);
 const allDone=()=>C.modules.every(complete);
 const bestExam=()=>Math.max(0,...state.exam.attempts.map(a=>a.percent));
 const passed=()=>state.exam.attempts.length>0&&bestExam()>=C.pass;
 const units=()=>C.modules.reduce((n,m)=>n+steps(m).filter(Boolean).length,0)+(passed()?1:0);
 const percent=()=>Math.round(units()/49*100);
 const duration=(n,seconds=false)=>{n=Math.floor(n);return (n>=3600?`${Math.floor(n/3600)}h `:'')+`${Math.floor(n%3600/60)}m`+(seconds?` ${String(n%60).padStart(2,'0')}s`:'');};
 function announce(t){$('#live').textContent=t;}
 function setFeedback(id,text,error=false){feedback[id]={text,error};announce(text);}
 function fb(id){return feedback[id]?`<div class="feedback ${feedback[id].error?'error':'success'}" role="status">${esc(feedback[id].text)}</div>`:'';}
 function coaching(text){return `<div class="coaching"><strong>Coaching Key Points</strong>${esc(text)}</div>`;}
 function nav(){
 $('#sidebar').innerHTML=`<div class="progress-card"><p class="eyebrow">Your Progress</p><strong>${percent()}% Complete</strong><p>${C.modules.filter(complete).length} of 12 Modules Complete</p><div class="progress-track" role="progressbar" aria-label="Course progress" aria-valuemin="0" aria-valuemax="100" aria-valuenow="${percent()}"><span style="width:${percent()}%"></span></div></div><nav><button class="nav-btn ${state.route==='welcome'?'active':''}" data-route="welcome" ${state.route==='welcome'?'aria-current="page"':''}><span class="num" aria-hidden="true">⌂</span><span><strong>Your Learning Journey</strong><small>Course Overview</small></span></button>${C.modules.map((m,i)=>`<button class="nav-btn ${state.route===m.id?'active':''} ${complete(m)?'done':''}" data-route="${m.id}" ${state.route===m.id?'aria-current="page"':''}><span class="num" aria-hidden="true">${complete(m)?'✓':String(i+1).padStart(2,'0')}</span><span><strong>${esc(titleText(m.short))}</strong><small>${steps(m).filter(Boolean).length}/4 Learning Steps${complete(m)?' · Complete':''}</small></span></button>`).join('')}<button class="nav-btn ${state.route==='exam'?'active':''}" data-route="exam" ${state.route==='exam'?'aria-current="page"':''}><span class="num" aria-hidden="true">◎</span><span><strong>Knowledge Check</strong><small>${state.exam.attempts.length?`Best Score ${bestExam()}%`:'20 Questions · 80% To Pass'}</small></span></button><button class="nav-btn ${state.route==='certificate'?'active':''}" data-route="certificate" ${state.route==='certificate'?'aria-current="page"':''}><span class="num" aria-hidden="true">♧</span><span><strong>Certificate & Answers</strong><small>Keep A Record Of Your Learning</small></span></button></nav><div class="nav-footer">Progress saves in this browser.<br>Use fictional information only.</div>`;
 $('#topProgress').style.width=percent()+'%';
 }
 function applyPanel(){const collapsed=state.collapsed??matchMedia('(max-width:760px)').matches;document.body.classList.toggle('collapsed',collapsed);const b=$('#panelToggle');b.setAttribute('aria-expanded',String(!collapsed));b.setAttribute('aria-label',collapsed?'Show course navigation':'Hide course navigation');b.title=collapsed?'Show course navigation':'Hide course navigation';}
 function header(kicker,title,intro,meta=''){return `<div class="lesson-header"><p class="eyebrow">${esc(titleText(kicker))}</p><h1>${esc(titleText(title))}</h1>${meta}<p class="intro">${esc(intro)}</p></div>`;}
 function welcome(){return header('Healthcare billing foundations','Every claim begins with a patient.','Follow the journey from care to claim to payment—and understand the people and information behind every stage.','<div class="lesson-meta"><span>12 modules</span><span>•</span><span>Approx. 2 hours, at your pace</span><span>•</span><span>Foundational learning</span></div>')+`<div class="card"><p class="section-label">Your learning journey</p><h2>See how the pieces connect</h2><div class="journey"><div><span class="step-number">01 / CARE</span><strong>A patient needs care</strong><span>A provider delivers and documents the service.</span></div><div><span class="step-number">02 / CLAIM</span><strong>The service becomes a claim</strong><span>The payer evaluates coverage and reimbursement.</span></div><div><span class="step-number">03 / PAYMENT</span><strong>The account moves forward</strong><span>Payer and patient payments connect to the full revenue cycle.</span></div></div><p>Build a working vocabulary before moving into insurance follow-up or denial management. Explore professional and hospital billing, find fields on real blank claim forms, and finish with an overview of Revenue Cycle Management.</p><div class="actions"><button class="btn primary" data-route="${C.modules.find(m=>!complete(m))?.id||'exam'}">${units()>0?'Continue learning':'Begin with the HIPAA refresher'} <span aria-hidden="true">→</span></button><span class="small muted">Pick up where you leave off.</span></div></div><div class="card"><h2>Make this course your own</h2><div class="welcome-list"><div><strong>Learn, practice, check, reflect</strong><p>Each module has four steps. Practice has retries and coaching. Answer both short check questions correctly to complete the module.</p></div><div><strong>Earn a completion certificate</strong><p>Complete all twelve modules and score at least 80% on the 20-question knowledge check. Retakes are available.</p></div><div><strong>Your work stays in this browser</strong><p>Answers and progress save as you work. They do not sync between devices. You can download a PDF record at any point.</p></div><div><strong>Time counts while you learn</strong><p>The timer pauses when the page is hidden, unfocused or idle for 90 seconds. Long sleep gaps are excluded.</p></div></div><p class="notice" style="margin-top:20px">All scenarios are fictional. Do not enter patient information. This is a foundations course, not a substitute for your organization’s policies or current payer instructions.</p></div><div class="card"><h2>Reference desk</h2><p>Core definitions were checked against these public resources. Claim-form practice uses only the first page of your supplied PDFs.</p><ul class="sources">${C.sources.map(([t,u])=>`<li><a href="${u}" target="_blank" rel="noopener">${esc(t)} ↗</a></li>`).join('')}</ul></div>`;}
 function activityInner(m){const a=as(m),d=m.activity,id=m.id;let html='';
 if(d.type==='flip'){a.seen??=[];html=`<div class="flip-grid">${d.items.map(([term,meaning],i)=>`<button class="flip ${a.seen.includes(i)?'open':''}" data-act="flip" data-index="${i}" aria-expanded="${a.seen.includes(i)}"><strong>${esc(term)}</strong>${a.seen.includes(i)?`<span>${esc(meaning)}</span><small>✓ Explored</small>`:'<small>Explore concept <span aria-hidden="true">↗</span></small>'}</button>`).join('')}</div><p class="save-note">${a.seen.length} of ${d.items.length} concepts explored.</p>`;}
 if(d.type==='sort'){a.placements??={};const token=i=>`<button class="token ${selectedToken===i?'selected':''}" draggable="false" data-act="token" data-index="${i}" aria-pressed="${selectedToken===i}" ${a.done?'disabled':''}>${esc(d.items[i][0])}</button>`;html=`<div class="bank" aria-label="Unsorted cards">${d.items.map((_,i)=>a.placements[i]===undefined?token(i):'').join('')||'<span class="small muted">All cards placed. Check your sort when ready.</span>'}</div><div class="buckets ${d.buckets.length===2?'two':''}">${d.buckets.map((b,j)=>`<div class="bucket" data-bucket="${j}"><button class="bucket-button" data-act="bucket" data-index="${j}" ${a.done?'disabled':''}>${esc(b)}</button>${d.items.map((_,i)=>a.placements[i]===j?token(i):'').join('')}</div>`).join('')}</div>${!a.done?'<div class="actions"><button class="btn primary" data-act="check-sort">Check my sort</button><span class="small muted">To move a placed card, select it again.</span></div>':''}`;}
 if(d.type==='match'){a.pairs??={};const order=d.pairs.map((_,i)=>(i+2)%d.pairs.length);html=`<div class="match-area"><svg class="match-lines" aria-hidden="true"></svg><div class="match-col">${d.pairs.map(([t],i)=>`<button class="match-btn ${a.pairs[i]!==undefined?'paired':''} ${selectedLeft===i?'selected':''}" data-act="match-left" data-index="${i}" aria-pressed="${selectedLeft===i}" ${a.done?'disabled':''}>${esc(t)}</button>`).join('')}</div><div class="match-col">${order.map(i=>{const pair=Object.keys(a.pairs).find(k=>a.pairs[k]===i);return `<button class="match-btn ${pair!==undefined?'paired':''}" data-act="match-right" data-index="${i}" ${a.done?'disabled':''}>${esc(d.pairs[i][1])}</button>`;}).join('')}</div></div><p class="save-note">${Object.keys(a.pairs).length} of ${d.pairs.length} pairs connected.</p>${!a.done?'<button class="btn primary" data-act="check-match">Check My Connections</button>':''}`;}
 if(d.type==='sequence'){html=`<ol class="sequence">${a.order.map((x,i)=>`<li><span class="position">${i+1}</span><strong>${esc(d.items[x])}</strong><button class="icon-btn" data-act="move-up" data-index="${i}" aria-label="Move ${esc(d.items[x])} up" ${i===0||a.done?'disabled':''}>↑</button><button class="icon-btn" data-act="move-down" data-index="${i}" aria-label="Move ${esc(d.items[x])} down" ${i===a.order.length-1||a.done?'disabled':''}>↓</button></li>`).join('')}</ol>${!a.done?'<button class="btn primary" data-act="check-sequence">Check the sequence</button>':''}`;}
 if(d.type==='simulation'){
 a.index??=0;a.history??=[];const step=d.steps[a.index];
 html=`<div class="sim-progress" aria-label="${a.done?d.steps.length:a.index} of ${d.steps.length} decisions completed">${d.steps.map((_,i)=>`<span class="${i<a.index||a.done?'done':''}"></span>`).join('')}</div>`;
 if(a.done)html+='<h3>Conversation completed</h3><p>You guided Maria through eligibility, authorization and payer order.</p>';
 else {html+=`<p class="eyebrow">Decision ${a.index+1} of ${d.steps.length}</p><h3>${esc(step.question)}</h3>`;
 if(a.awaiting)html+=`<div class="feedback success">${esc(step.right)}</div><div class="actions"><button class="btn primary" data-act="sim-next">${a.index===d.steps.length-1?'Finish conversation':'Continue conversation'} →</button></div>`;
 else html+=`<div class="sim-options">${step.options.map((s,i)=>`<button class="sim-option" data-act="sim-choice" data-index="${i}">${esc(s)}</button>`).join('')}</div>`;
 }
 }
 if(d.type==='forms'){html=formActivity(m);}
 if(d.explanation&&a.done){html+=`<div class="activity-explanation"><label class="field-label" for="activityExplanation">${esc(d.explanation)}</label><textarea id="activityExplanation" maxlength="3000" placeholder="Explain your reasoning in at least 20 characters. Do not include patient information.">${esc(a.explanation||'')}</textarea><p class="save-note">Your explanation saves as you type. Submit it to complete this practice.</p><button class="btn ${a.explanationSubmitted?'':'primary'}" data-act="save-explanation">${a.explanationSubmitted?'Update Explanation':'Submit Explanation'}</button></div>`;}
 return html+fb('activity-'+id)+(activityDone(m)?coaching(d.coaching):'');
 }
 function formActivity(m){
  const a=as(m),f=C.forms.find(x=>x.id===a.tab),s=a.forms[f.id],prompt=f.prompts[s.index];
  if(s.done)return `<div class="form-tabs" role="group" aria-label="Select claim form">${C.forms.map(x=>`<button class="btn ${a.tab===x.id?'active':''}" data-act="form-tab" data-form="${x.id}" aria-pressed="${a.tab===x.id}">${x.id==='cms'?'CMS-1500':'UB-04'} ${a.forms[x.id].done?'✓':''}</button>`).join('')}</div><div class="form-resource"><h3>${esc(titleText(f.name))}</h3><p>${esc(f.note)}</p><div class="actions"><a class="btn primary" href="${f.image}" target="_blank" rel="noopener">View Supplied First Page ↗</a><a class="btn" href="${f.official}" target="_blank" rel="noopener">${esc(f.officialLabel)} ↗</a></div></div><div class="feedback success">All ${f.id==='cms'?'CMS-1500 boxes':'UB-04 form locators'} in this set are complete.</div>`;
  const answer=prompt[1],answerIndex=f.fields.findIndex(x=>x[0]===answer),fieldLabel=f.fields[answerIndex][1];
  const optionIndexes=[answerIndex,(answerIndex+3)%f.fields.length,(answerIndex+6)%f.fields.length,(answerIndex+9)%f.fields.length].sort((x,y)=>f.fields[x][0].localeCompare(f.fields[y][0],undefined,{numeric:true}));
  return `<div class="form-tabs" role="group" aria-label="Select claim form">${C.forms.map(x=>`<button class="btn ${a.tab===x.id?'active':''}" data-act="form-tab" data-form="${x.id}" aria-pressed="${a.tab===x.id}">${x.id==='cms'?'CMS-1500':'UB-04'} ${a.forms[x.id].done?'✓':''}</button>`).join('')}</div><div class="form-resource"><h3>${esc(titleText(f.name))}</h3><p>${esc(f.note)}</p><div class="actions"><a class="btn primary" href="${f.image}" target="_blank" rel="noopener">View Supplied First Page ↗</a><a class="btn" href="${f.official}" target="_blank" rel="noopener">${esc(f.officialLabel)} ↗</a></div></div><div class="form-prompt"><small>Question ${s.index+1} of ${f.prompts.length} · ${f.id==='cms'?'CMS-1500 Box':'UB-04 Form Locator'}</small><strong>Which ${f.id==='cms'?'box':'form locator'} would you use to enter or locate the ${esc(fieldLabel.toLowerCase())}?</strong></div><fieldset class="form-question"><legend class="sr-only">Choose the correct ${f.id==='cms'?'box':'form locator'}.</legend>${optionIndexes.map(i=>`<label class="choice locator-choice"><input type="radio" name="form-answer" data-form-answer value="${f.fields[i][0]}" ${s.answer===f.fields[i][0]?'checked':''} ${s.awaiting?'disabled':''}><span>${esc(f.fields[i][0])}</span></label>`).join('')}</fieldset>${s.awaiting?`<div class="feedback success">Correct. ${esc(answer)} is the ${f.id==='cms'?'box':'form locator'} for ${esc(fieldLabel.toLowerCase())}.</div><button class="btn primary" data-act="form-next">${s.index===f.prompts.length-1?'Finish This Form':'Next Question'} →</button>`:'<button class="btn primary" data-act="check-form">Check Answer</button>'}`;
 }
 function cfuHTML(m){const s=ms(m.id).cfu,done=cfuDone(m),latest=s.attempts.at(-1);return `<p class="section-label">Step 3 / Check For Understanding</p><h2>Check Your Understanding</h2><p>Two questions to confirm the essentials. Both must be correct; retries are welcome.</p>${m.cfu.map((q,i)=>`<fieldset><legend>${i+1}. ${esc(q[0])}</legend>${q[1].map((o,j)=>`<label class="choice"><input type="radio" name="cfu-${i}" data-cfu="${i}" value="${j}" ${s.answers[i]===j?'checked':''} ${done?'disabled':''}><span>${esc(o)}</span></label>`).join('')}${latest?`<p class="feedback ${latest.answers[i]===q[2]?'success':'error'}">${latest.answers[i]===q[2]?'Correct.':'Review this concept.'} ${esc(q[3])}</p>`:''}</fieldset>`).join('')}${done?`<span class="completed-badge">✓ Check Complete · 2/2</span>${coaching(m.cfu.map(q=>q[3]).join(' '))}`:'<button class="btn primary" data-act="check-cfu">Check My Answers</button>'}${fb('cfu-'+m.id)}${latest?`<p class="save-note">First Attempt: ${s.attempts[0].score}/2 · Best: ${Math.max(...s.attempts.map(x=>x.score))}/2 · Attempts: ${s.attempts.length}</p>`:''}`;}
 function reflectionHTML(m){const r=ms(m.id).reflection;return `<p class="section-label">Step 4 / Reflect</p><h2>Make The Connection</h2><label class="field-label" for="reflection">${esc(m.reflection)}</label><textarea id="reflection" maxlength="3000" placeholder="Explain your thinking in at least 20 characters. Do not include patient information.">${esc(r.text)}</textarea><p class="save-note" id="draftNote">Your draft saves as you type. Submit your response to complete this reflection.</p><button class="btn ${reflectionDone(m)?'':'primary'}" data-act="save-reflection">${reflectionDone(m)?'Update Reflection':'Submit Reflection'}</button>${fb('reflection-'+m.id)}${reflectionDone(m)?coaching('Use the lesson’s distinctions to explain your reasoning. '+m.activity.coaching):''}`;}
 function moduleHTML(m){const idx=C.modules.indexOf(m),s=ms(m.id);return header(`Module ${String(idx+1).padStart(2,'0')} / ${m.kicker}`,m.title,m.intro,`<div class="lesson-meta"><span>${m.time} Min Suggested</span><span>•</span><span>Four Learning Steps</span>${complete(m)?'<span class="completed-badge">✓ Complete</span>':''}</div>`)+`<div class="objective"><strong>By The End Of This Module</strong>${esc(m.objective)}</div><div class="card" id="lesson"><p class="section-label">Step 1 / Learn</p>${m.sections.map(([h,p])=>`<section class="lesson-section"><h3>${esc(titleText(h))}</h3><p>${esc(p)}</p></section>`).join('')}<label class="acknowledge"><input type="checkbox" data-read ${s.read?'checked':''}><span>I Have Reviewed This Lesson</span></label></div><div class="card" id="activity"><p class="section-label">Step 2 / Practice · ${titleText(m.activity.type==='forms'?'Form Navigation':({flip:'Explore',sort:'Bucket Sort',match:'Connect Pairs',sequence:'Sequence',simulation:'Decision Simulation'}[m.activity.type]))}</p><h2>${esc(titleText(m.activity.title))}</h2>${m.activity.prompt?`<p class="instruction">${esc(m.activity.prompt)}</p>`:''}<div id="activityBody">${activityInner(m)}</div></div><div class="card" id="cfu">${cfuHTML(m)}</div><div class="card" id="reflectionCard">${reflectionHTML(m)}</div><div id="moduleStatus">${statusHTML(m)}</div><div class="lesson-footer"><button class="btn" data-route="${idx===0?'welcome':C.modules[idx-1].id}">← Back</button><button class="btn primary" data-route="${idx===C.modules.length-1?'exam':C.modules[idx+1].id}">${idx===C.modules.length-1?'Go To Knowledge Check':'Next Module'} →</button></div>`;}
 function statusHTML(m){const s=steps(m);return `<div class="section-progress">${['Lesson Reviewed','Practice Complete','Check Passed','Reflection Submitted'].map((t,i)=>`<span class="${s[i]?'met':''}">${s[i]?'✓':'○'} ${t}</span>`).join('')}</div><p class="completion-message">${complete(m)?'Module complete. Your work is saved.':'Complete all four steps to mark this module complete.'}</p>`;}
 function examHTML(){if(!allDone())return header('Knowledge Check','Bring Your Learning Together','Complete all twelve modules to unlock the graded knowledge check.')+`<div class="card"><h2>Your Next Step</h2><p>${C.modules.filter(complete).length} of 12 modules complete. Each module needs the lesson acknowledgement checked, practice completed, both check questions correct, and a reflection submitted.</p><button class="btn primary" data-route="${C.modules.find(m=>!complete(m)).id}">Continue Your Course →</button></div>`;
 const e=state.exam,q=C.exam[e.index],last=e.attempts.at(-1);if(e.submitted&&last){return header('Knowledge check',last.percent>=C.pass?'You’ve passed the knowledge check.':'Review, then try again.',`Your score: ${last.percent}% · ${last.score} of ${C.exam.length} correct. Passing score: ${C.pass}%.`)+`<div class="card"><div class="stats"><div class="stat"><strong>${last.percent}%</strong><span>Latest score</span></div><div class="stat"><strong>${bestExam()}%</strong><span>Best score</span></div><div class="stat"><strong>${e.attempts.length}</strong><span>Attempt${e.attempts.length===1?'':'s'}</span></div></div>${coaching('A claim connects patient, provider, service and payer information. Confirm roles and requirements, distinguish reporting from payment, and connect upstream accuracy to downstream results.')}<div class="actions"><button class="btn primary" data-route="certificate">${passed()?'View my certificate':'View my learning record'} →</button><button class="btn" data-act="retake">Retake knowledge check</button></div></div><div class="card"><h2>Review your answers</h2>${C.exam.map((x,i)=>`<div class="review-item"><p><strong>${i+1}. ${esc(x[0])}</strong></p><p class="small">Your answer: ${esc(x[1][last.answers[i]])}</p><p class="feedback ${last.answers[i]===x[2]?'success':'error'}">${last.answers[i]===x[2]?'Correct.':`Correct answer: ${esc(x[1][x[2]])}.`} ${esc(x[3])}</p></div>`).join('')}</div>`;}
 return header('Knowledge check','Apply what you’ve learned','Answer all twenty questions, then submit. Your selections save immediately. You can revisit questions before submission.',`<div class="lesson-meta"><span>80% to pass</span><span>•</span><span>Untimed assessment</span></div>`)+`<div class="card"><p class="eyebrow">Question ${e.index+1} of ${C.exam.length} · ${esc(q[4])}</p><fieldset><legend>${esc(q[0])}</legend>${q[1].map((o,i)=>`<label class="choice"><input type="radio" name="exam" data-exam="${e.index}" value="${i}" ${e.answers[e.index]===i?'checked':''}><span>${esc(o)}</span></label>`).join('')}</fieldset><div class="actions"><button class="btn" data-act="exam-prev" ${e.index===0?'disabled':''}>← Previous</button><button class="btn primary" data-act="exam-next" ${e.index===C.exam.length-1?'disabled':''}>Next →</button></div><div class="exam-dots" role="group" aria-label="Jump to assessment question">${C.exam.map((_,i)=>`<button data-act="exam-jump" data-index="${i}" class="${e.index===i?'active':''} ${e.answers[i]!==undefined&&e.answers[i]!==null?'answered':''}" aria-label="Question ${i+1}, ${e.answers[i]!==undefined&&e.answers[i]!==null?'answered':'unanswered'}" ${e.index===i?'aria-current="step"':''}>${i+1}</button>`).join('')}</div><p class="save-note">${e.answers.filter(x=>Number.isInteger(x)).length} of 20 answered.</p><button class="btn teal" data-act="submit-exam">Submit knowledge check</button>${fb('exam')}</div>`;
 }
 function certificateHTML(){const cfuBest=C.modules.reduce((n,m)=>n+Math.max(0,...ms(m.id).cfu.attempts.map(a=>a.score)),0),cfuFirst=C.modules.reduce((n,m)=>n+(ms(m.id).cfu.attempts[0]?.score||0),0),eligible=allDone()&&passed();return header('Your learning record',eligible?'A foundation to build on.':'Your progress, in one place.',eligible?'You’ve completed Healthcare Billing Foundations. Personalize your certificate and keep a copy of your learning.':'Continue learning, or download a record of the answers you’ve saved so far.')+`<div class="card"><h2>Course results</h2><div class="stats"><div class="stat"><strong>${C.modules.filter(complete).length}/12</strong><span>Modules complete</span></div><div class="stat"><strong>${cfuBest}/24</strong><span>Best module checks<br>First attempts: ${cfuFirst}/24</span></div><div class="stat"><strong>${state.exam.attempts.length?bestExam()+'%':'—'}</strong><span>Best knowledge check</span></div></div><p class="small muted">Module checks and the graded knowledge check are reported separately. Best results across retries count toward completion.</p><p>Time invested: <strong>${duration(elapsed,true)}</strong></p><label class="field-label" for="learnerName">Name for your learning record</label><input id="learnerName" type="text" maxlength="80" autocomplete="name" value="${esc(state.name)}" placeholder="Enter your name"><p class="save-note">Your name is saved only in this browser.</p>${eligible?`<canvas id="certificateCanvas" class="certificate" width="1600" height="1100" role="img" aria-label="Completion certificate for Healthcare Billing Foundations. Name: ${esc(state.name||'not yet entered')}. Knowledge check: ${bestExam()} percent. Time invested: ${duration(elapsed)}."></canvas><button class="btn primary" data-act="download-png">Download certificate PNG</button>${fb('certificate')}`:`<p class="notice" style="margin-top:20px">The certificate unlocks after all modules are complete and your knowledge-check score reaches 80%.</p><div class="actions"><button class="btn primary" data-route="${C.modules.find(m=>!complete(m))?.id||'exam'}">Continue learning →</button></div>`}</div><div class="card"><h2>Keep your answers</h2><p>Download every reflection, activity result, module check and assessment attempt in one PDF. Incomplete work is included and labeled.</p><button class="btn" data-act="download-pdf">Download PDF of my answers <span aria-hidden="true">↓</span></button><p class="save-note">PDF export needs an internet connection to load the PDF library. The rest of the course uses local assets.</p>${fb('pdf')}</div>`;}
 function render(focus=false){nav();applyPanel();const m=C.modules.find(x=>x.id===state.route);$('#main').innerHTML=m?moduleHTML(m):state.route==='exam'?examHTML():state.route==='certificate'?certificateHTML():welcome();document.title=titleText(m?m.title:state.route==='exam'?'Knowledge Check':state.route==='certificate'?'Certificate & Answers':C.title);if(m?.activity.type==='match')requestAnimationFrame(drawLines);if(state.route==='certificate')drawCertificate();if(focus){window.scrollTo({top:0,behavior:'instant'});$('#main').focus({preventScroll:true});}}
 function updateActivity(m){const scroll=$('.form-scroll')?{top:$('.form-scroll').scrollTop,left:$('.form-scroll').scrollLeft}:null;$('#activityBody').innerHTML=activityInner(m);if(scroll&&$('.form-scroll')){$('.form-scroll').scrollTop=scroll.top;$('.form-scroll').scrollLeft=scroll.left;}nav();$('#moduleStatus').innerHTML=statusHTML(m);if(m.activity.type==='match')requestAnimationFrame(drawLines);}
 function drawLines(){const m=C.modules.find(x=>x.id===state.route);if(!m||m.activity.type!=='match')return;const area=$('.match-area'),svg=$('.match-lines');if(!area||!svg)return;const rect=area.getBoundingClientRect();svg.innerHTML=Object.entries(as(m).pairs).map(([l,r])=>{const a=$(`[data-act="match-left"][data-index="${l}"]`).getBoundingClientRect(),b=$(`[data-act="match-right"][data-index="${r}"]`).getBoundingClientRect();return `<line x1="${a.right-rect.left}" y1="${a.top+a.height/2-rect.top}" x2="${b.left-rect.left}" y2="${b.top+b.height/2-rect.top}"/>`;}).join('');}
 function go(route){state.route=route;selectedToken=null;selectedLeft=null;feedback={};if(matchMedia('(max-width:760px)').matches)state.collapsed=true;save();render(true);}
 $('#panelToggle').addEventListener('click',()=>{state.collapsed=!document.body.classList.contains('collapsed');save();applyPanel();requestAnimationFrame(drawLines);});
 function place(m,i){const a=as(m);if(selectedToken===null){setFeedback('activity-'+m.id,'Select a card first, then choose its bucket.',true);}else{a.placements[selectedToken]=i;selectedToken=null;delete feedback['activity-'+m.id];save();}updateActivity(m);}
 document.addEventListener('click',async ev=>{
 const route=ev.target.closest('[data-route]');if(route){go(route.dataset.route);return;}
 const b=ev.target.closest('[data-act]');if(!b||b.disabled)return;const action=b.dataset.act,i=Number(b.dataset.index),m=C.modules.find(x=>x.id===state.route),s=m?ms(m.id):null,a=m?as(m):null,d=m?.activity;
 if(action==='download-pdf'){await exportPDF();return;}
 if(action==='download-png'){if(!state.name.trim()){setFeedback('certificate','Enter your name before downloading the certificate.',true);render();$('#learnerName').focus();return;}await drawCertificate();const c=$('#certificateCanvas');c.toBlob(blob=>{if(blob)download(blob,'healthcare-billing-foundations-certificate.png');},'image/png');return;}
 if(action==='retake'){state.exam.answers=[];state.exam.index=0;state.exam.submitted=false;delete feedback.exam;save();render(true);return;}
 if(action.startsWith('exam-')){const e=state.exam;e.index=action==='exam-next'?Math.min(19,e.index+1):action==='exam-prev'?Math.max(0,e.index-1):i;save();render(true);return;}
 if(action==='submit-exam'){if(!allDone())return;const e=state.exam,missing=C.exam.findIndex((q,i)=>!Number.isInteger(e.answers[i]));if(missing!==-1){e.index=missing;setFeedback('exam',`Answer every question before submitting. Question ${missing+1} is unanswered.`,true);save();render(true);return;}const score=C.exam.filter((q,i)=>e.answers[i]===q[2]).length;e.attempts.push({answers:[...e.answers],score,percent:Math.round(score/20*100),date:new Date().toISOString()});e.submitted=true;if(passed()&&!state.completedAt){state.completedAt=new Date().toISOString();}save();render(true);return;}
 if(!m)return;
 if(action==='save-explanation'){if((a.explanation||'').trim().length<20){setFeedback('activity-'+m.id,'Write at least 20 characters before submitting your explanation.',true);}else{a.explanationSubmitted=true;setFeedback('activity-'+m.id,'Explanation submitted. Review the coaching points below.');save();}updateActivity(m);return;}
 if(action==='check-cfu'){if(m.cfu.some((_,j)=>!Number.isInteger(s.cfu.answers[j]))){setFeedback('cfu-'+m.id,'Choose an answer for both questions before checking.',true);}else{const score=m.cfu.filter((q,j)=>s.cfu.answers[j]===q[2]).length;s.cfu.attempts.push({answers:[...s.cfu.answers],score,date:new Date().toISOString()});setFeedback('cfu-'+m.id,score===2?'Both answers are correct. Check complete.':`${score} of 2 correct. Review the explanations and try again.`,score!==2);save();}$('#cfu').innerHTML=cfuHTML(m);nav();$('#moduleStatus').innerHTML=statusHTML(m);return;}
 if(action==='save-reflection'){if(s.reflection.text.trim().length<20){setFeedback('reflection-'+m.id,'Write at least 20 characters before submitting this reflection.',true);}else{s.reflection.submitted=true;setFeedback('reflection-'+m.id,'Reflection submitted. Review the coaching points below.');save();}$('#reflectionCard').innerHTML=reflectionHTML(m);nav();$('#moduleStatus').innerHTML=statusHTML(m);return;}
 if(action==='flip'){a.seen??=[];if(!a.seen.includes(i))a.seen.push(i);a.done=a.seen.length===d.items.length;}
 if(action==='token'){selectedToken=selectedToken===i?null:i;}
 if(action==='bucket'){place(m,i);return;}
 if(action==='check-sort'){const placed=Object.keys(a.placements).length,correct=d.items.filter((x,j)=>a.placements[j]===x[1]).length;a.attempts??=[];if(placed<d.items.length)setFeedback('activity-'+m.id,'Place every card in a bucket before checking.',true);else{a.attempts.push({placements:{...a.placements},correct});a.done=correct===d.items.length;setFeedback('activity-'+m.id,a.done?'All cards are in the correct categories.':`${correct} of ${d.items.length} correct. Review the lesson and move any cards that need a different category.`,!a.done);}}
 if(action==='match-left'){selectedLeft=selectedLeft===i?null:i;}
 if(action==='match-right'){if(selectedLeft===null)setFeedback('activity-'+m.id,'Choose a term first, then a definition.',true);else{for(const k of Object.keys(a.pairs))if(a.pairs[k]===i)delete a.pairs[k];a.pairs[selectedLeft]=i;selectedLeft=null;delete feedback['activity-'+m.id];}}
 if(action==='check-match'){const correct=d.pairs.filter((_,j)=>a.pairs[j]===j).length;if(Object.keys(a.pairs).length!==d.pairs.length)setFeedback('activity-'+m.id,'Connect every term before checking.',true);else{a.attempts??=[];a.attempts.push({pairs:{...a.pairs},correct});a.done=correct===d.pairs.length;setFeedback('activity-'+m.id,a.done?'All unique pairs are correctly connected.':`${correct} of ${d.pairs.length} pairs correct. Select a term and a new definition to revise.`,!a.done);}}
 if(action==='move-up'||action==='move-down'){const j=action==='move-up'?i-1:i+1;if(j>=0&&j<a.order.length)[a.order[i],a.order[j]]=[a.order[j],a.order[i]];delete feedback['activity-'+m.id];}
 if(action==='check-sequence'){const correct=a.order.filter((x,j)=>x===j).length;a.attempts??=[];a.attempts.push({order:[...a.order],correct});a.done=correct===d.items.length;setFeedback('activity-'+m.id,a.done?'The six stages are in the correct sequence.':`${correct} of 6 stages are in the right position. Think about what must happen before the payer can evaluate a claim.`,!a.done);}
 if(action==='sim-choice'){const step=d.steps[a.index],correct=i===step.correct;a.history.push({step:a.index,choice:i,correct});a.awaiting=correct;setFeedback('activity-'+m.id,correct?step.right:step.wrong,!correct);}
 if(action==='sim-next'){if(!a.awaiting)return;a.awaiting=false;delete feedback['activity-'+m.id];if(a.index===d.steps.length-1)a.done=true;else a.index++;}
 if(action==='form-tab'){a.tab=b.dataset.form;delete feedback['activity-'+m.id];}
 if(action==='check-form'){const f=C.forms.find(x=>x.id===a.tab),fs=a.forms[f.id],expected=f.prompts[fs.index][1];if(!fs.answer){setFeedback('activity-'+m.id,`Choose a ${f.id==='cms'?'box':'form locator'} before checking.`,true);}else{const correct=fs.answer===expected;fs.history.push({prompt:fs.index,field:fs.answer,correct});fs.awaiting=correct;if(correct)delete feedback['activity-'+m.id];else setFeedback('activity-'+m.id,`${fs.answer} is not the correct ${f.id==='cms'?'box':'form locator'} for this question. Keep the form open and try again.`,true);}save();updateActivity(m);return;}
 if(action==='form-next'){const f=C.forms.find(x=>x.id===a.tab),fs=a.forms[f.id];if(!fs.awaiting)return;fs.awaiting=false;fs.answer=null;delete feedback['activity-'+m.id];if(fs.index===f.prompts.length-1){fs.done=true;a.done=C.forms.every(x=>a.forms[x.id].done);if(!a.done)a.tab=C.forms.find(x=>!a.forms[x.id].done).id;}else fs.index++;}
 save();updateActivity(m);
 // Keep keyboard users at the control they activated after local re-rendering.
 if(['flip','token','match-left','match-right','move-up','move-down'].includes(action)){const idx=action==='move-up'?Math.max(0,i-1):action==='move-down'?Math.min(a.order.length-1,i+1):i;const target=$(`[data-act="${action}"][data-index="${idx}"]`);if(target&&!target.disabled)target.focus({preventScroll:true});}
 });
 document.addEventListener('input',ev=>{const t=ev.target,m=C.modules.find(x=>x.id===state.route);if(t.id==='reflection'&&m){ms(m.id).reflection.text=t.value;ms(m.id).reflection.submitted=false;$('#draftNote').textContent='Draft saved. Submit your response when ready.';save();nav();$('#moduleStatus').innerHTML=statusHTML(m);}if(t.id==='activityExplanation'&&m){const a=as(m);a.explanation=t.value;a.explanationSubmitted=false;save();nav();$('#moduleStatus').innerHTML=statusHTML(m);}if(t.id==='learnerName'){state.name=t.value;save();drawCertificate();}});
 document.addEventListener('change',ev=>{const t=ev.target,m=C.modules.find(x=>x.id===state.route);if(t.dataset.read!==undefined&&m){ms(m.id).read=t.checked;save();nav();$('#moduleStatus').innerHTML=statusHTML(m);announce(t.checked?'Lesson acknowledged.':'Lesson acknowledgement removed.');}if(t.dataset.cfu!==undefined&&m){ms(m.id).cfu.answers[Number(t.dataset.cfu)]=Number(t.value);save();}if(t.dataset.formAnswer!==undefined&&m){const a=as(m),f=C.forms.find(x=>x.id===a.tab);a.forms[f.id].answer=t.value;save();}if(t.dataset.exam!==undefined){state.exam.answers[Number(t.dataset.exam)]=Number(t.value);save();const n=Number(t.dataset.exam);$(`[data-act="exam-jump"][data-index="${n}"]`)?.classList.add('answered');const note=$('.save-note');if(note)note.textContent=`${state.exam.answers.filter(x=>Number.isInteger(x)).length} of 20 answered.`;}});
 // Pointer fallback makes bucket dragging work on touch and browser engines without HTML drag events.
 let pointerDrag=null;
 document.addEventListener('pointerdown',ev=>{const t=ev.target.closest('.token');if(t&&!t.disabled)pointerDrag={index:Number(t.dataset.index),x:ev.clientX,y:ev.clientY,moved:false};});
 document.addEventListener('pointermove',ev=>{if(pointerDrag&&Math.hypot(ev.clientX-pointerDrag.x,ev.clientY-pointerDrag.y)>10){pointerDrag.moved=true;document.querySelectorAll('.bucket').forEach(b=>b.classList.remove('over'));document.elementFromPoint(ev.clientX,ev.clientY)?.closest('.bucket')?.classList.add('over');}});
 document.addEventListener('pointerup',ev=>{if(!pointerDrag)return;const drag=pointerDrag;pointerDrag=null;document.querySelectorAll('.bucket').forEach(b=>b.classList.remove('over'));const bucket=document.elementFromPoint(ev.clientX,ev.clientY)?.closest('.bucket'),m=C.modules.find(x=>x.id===state.route);if(drag.moved&&bucket&&m?.activity.type==='sort'&&!as(m).done){selectedToken=drag.index;place(m,Number(bucket.dataset.bucket));}});
 document.addEventListener('dragend',()=>{pointerDrag=null;});
 document.addEventListener('dragstart',ev=>{const t=ev.target.closest('.token');if(!t)return;selectedToken=Number(t.dataset.index);ev.dataTransfer.setData('text/plain',t.dataset.index);ev.dataTransfer.effectAllowed='move';});
 document.addEventListener('dragover',ev=>{const b=ev.target.closest('.bucket');if(b){ev.preventDefault();b.classList.add('over');}});
 document.addEventListener('dragleave',ev=>{ev.target.closest('.bucket')?.classList.remove('over');});
 document.addEventListener('drop',ev=>{const b=ev.target.closest('.bucket'),m=C.modules.find(x=>x.id===state.route);if(b&&m&&m.activity.type==='sort'&&!as(m).done){ev.preventDefault();const raw=ev.dataTransfer.getData('text/plain');if(/^\d+$/.test(raw)&&Number(raw)<m.activity.items.length){selectedToken=Number(raw);place(m,Number(b.dataset.bucket));}}});
 function download(blob,name){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),20000);}
 async function drawCertificate(){const canvas=$('#certificateCanvas');if(!canvas)return;await document.fonts.ready;if(!canvas.isConnected)return;const ctx=canvas.getContext('2d');ctx.clearRect(0,0,1600,1100);ctx.fillStyle='#fff';ctx.fillRect(0,0,1600,1100);ctx.fillStyle='#10354c';ctx.fillRect(0,0,1600,26);ctx.fillStyle='#0d8b98';ctx.fillRect(0,26,1600,8);ctx.strokeStyle='#d3e6e9';ctx.lineWidth=2;ctx.strokeRect(55,65,1490,980);ctx.textAlign='center';ctx.fillStyle='#007d8b';ctx.font='600 23px Proxima';ctx.fillText('CERTIFICATE OF COMPLETION',800,195);ctx.fillStyle='#12354d';ctx.font='700 64px Proxima';ctx.fillText('Healthcare Billing Foundations',800,320);ctx.fillStyle='#546f82';ctx.font='400 28px Proxima';ctx.fillText('Presented To',800,438);const name=state.name.trim()||'Your Name';let size=74;while(size>24){ctx.font=`600 ${size}px Proxima`;if(ctx.measureText(name).width<1320)break;size--;}ctx.fillStyle='#0c344c';ctx.fillText(name,800,550);ctx.strokeStyle='#43a9ad';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(450,596);ctx.lineTo(1150,596);ctx.stroke();ctx.font='400 26px Proxima';ctx.fillStyle='#546f82';ctx.fillText('Completed All 12 Modules And Passed The Graded Knowledge Check.',800,682);ctx.font='700 31px Proxima';ctx.fillStyle='#15384f';ctx.fillText(`Knowledge Check: ${bestExam()}%   •   Time Invested: ${duration(elapsed)}`,800,790);ctx.font='400 25px Proxima';const date=new Date(state.completedAt||Date.now()).toLocaleDateString(undefined,{year:'numeric',month:'long',day:'numeric'});ctx.fillText(date,800,865);ctx.font='400 20px Proxima';ctx.fillStyle='#546f82';ctx.fillText('Foundational Learning · Record Of Course Completion',800,958);canvas.setAttribute('aria-label',`Certificate of completion for ${name}. Healthcare Billing Foundations. Score ${bestExam()} percent. Time invested ${duration(elapsed)}. ${date}.`);}
 async function exportPDF(){const button=$('[data-act="download-pdf"]');if(button){button.disabled=true;button.textContent='Preparing your PDF…';}try{if(!window.jspdf?.jsPDF)throw Error('PDF library unavailable. Reconnect to the internet and reload the course, then try again. Your saved answers will remain.');const doc=new window.jspdf.jsPDF({unit:'mm',format:'a4'});await document.fonts.ready;
 const pageCanvas=document.createElement('canvas');pageCanvas.width=900;pageCanvas.height=1273;const pen=pageCanvas.getContext('2d');const margin=82,maxWidth=736;let y=92,pageCount=0;
 function cleanPage(){pen.fillStyle='#fff';pen.fillRect(0,0,900,1273);y=92;}cleanPage();
 function flushPage(){pen.fillStyle='#546f82';pen.font='400 14px Proxima, Arial';pen.fillText('Healthcare Billing Foundations | Page '+(++pageCount),82,1218);if(pageCount>1)doc.addPage();doc.addImage(pageCanvas.toDataURL('image/jpeg',.78),'JPEG',0,0,210,297,undefined,'MEDIUM');cleanPage();}
 function add(text,size=11,bold=false){const px=Math.round(size*2.25),lineHeight=Math.round(px*1.35);pen.font=`${bold?700:400} ${px}px Proxima, Arial`;const lines=[];for(const paragraph of String(text).split('\n')){let line='';for(const word of paragraph.split(/\s+/)){const test=line?line+' '+word:word;if(pen.measureText(test).width<=maxWidth){line=test;continue;}if(line)lines.push(line);line='';for(const ch of word){if(pen.measureText(line+ch).width>maxWidth){lines.push(line);line='';}line+=ch;}}lines.push(line);}for(const line of lines){if(y+lineHeight>1168)flushPage();pen.font=`${bold?700:400} ${px}px Proxima, Arial`;pen.fillStyle='#15384f';pen.fillText(line,margin,y);y+=lineHeight;}y+=10;}
 function block(text){if(y>1040)flushPage();add(text,15,true);}

 add(C.title+' - My Learning Record',20,true);add('Learner: '+(state.name.trim()||'Name not provided'));add('Exported: '+new Date().toLocaleString());add(`Progress: ${percent()}% | Modules: ${C.modules.filter(complete).length}/12 | Time Invested: ${duration(elapsed,true)}`);add(`Knowledge-Check Best: ${state.exam.attempts.length?bestExam()+'%':'Not submitted'}`);add('This record includes incomplete work, required explanations, reflections and all recorded submitted attempts.');
 for(const m of C.modules){const s=ms(m.id),a=as(m),d=m.activity;block(`${C.modules.indexOf(m)+1}. ${m.title}`);add(`Lesson: ${s.read?'reviewed':'not reviewed'} | Practice: ${a.done?'complete':'in progress / not started'} | Module: ${complete(m)?'complete':'incomplete'}`);add('Practice: '+d.title,12,true);
 if(d.type==='flip')d.items.forEach(([t,v],i)=>add(`${t}: ${(a.seen||[]).includes(i)?'explored - '+v:'not yet explored'}`));
 if(d.type==='sort'){d.items.forEach(([t,correct],i)=>add(`${t} -> ${d.buckets[a.placements?.[i]]||'not placed'} (expected: ${d.buckets[correct]})`));(a.attempts||[]).forEach((at,j)=>add(`Sort attempt ${j+1}: ${at.correct}/${d.items.length}. `+d.items.map(([t],i)=>`${t}: ${d.buckets[at.placements[i]]||'unplaced'}`).join('; ')));}
 if(d.type==='match'){d.pairs.forEach(([t,v],i)=>add(`${t} -> ${d.pairs[a.pairs?.[i]]?.[1]||'not connected'} (expected: ${v})`));(a.attempts||[]).forEach((at,j)=>add(`Matching attempt ${j+1}: ${at.correct}/${d.pairs.length}. `+d.pairs.map(([t],i)=>`${t}: ${d.pairs[at.pairs[i]]?.[1]||'unconnected'}`).join('; ')));}
 if(d.type==='sequence'){add('Current order: '+a.order.map(i=>d.items[i]).join(' -> '));(a.attempts||[]).forEach((at,j)=>add(`Sequence attempt ${j+1}: ${at.correct}/6. `+at.order.map(i=>d.items[i]).join(' -> ')));}
 if(d.type==='simulation'){add(`Current decision: ${a.index+1}/${d.steps.length}`);(a.history||[]).forEach((h,i)=>add(`Decision attempt ${i+1}: ${d.steps[h.step].question} Response: ${d.steps[h.step].options[h.choice]}. ${h.correct?'Correct. '+d.steps[h.step].right:'Retry. '+d.steps[h.step].wrong}`));}
 if(d.type==='forms')for(const f of C.forms){const fs=a.forms[f.id];add(`${f.name}: ${fs.done?'complete':`${fs.index} of ${f.prompts.length} prompts completed`}`,11,true);fs.history.forEach(h=>add(`${f.prompts[h.prompt][0]} Selected field ${h.field}. ${h.correct?'Correct':'Retry; expected '+f.prompts[h.prompt][1]}.`));}
 if(d.explanation)add(`Required Explanation: ${a.explanation?.trim()||'No explanation entered.'}${a.explanationSubmitted?'':' (Draft not submitted)'}`,12,true);
 if(a.done)add('Coaching Key Points: '+d.coaching);
 add('Check for Understanding',12,true);m.cfu.forEach((q,i)=>add(`${i+1}. ${q[0]} Current answer: ${q[1][s.cfu.answers[i]]||'unanswered'}.`));if(!s.cfu.attempts.length)add('No submitted check attempts.');s.cfu.attempts.forEach((at,j)=>{add(`Attempt ${j+1}: ${at.score}/2 - ${new Date(at.date).toLocaleString()}`,11,true);m.cfu.forEach((q,i)=>add(`Answer ${i+1}: ${q[1][at.answers[i]]}. ${at.answers[i]===q[2]?'Correct.':'Review. '}${q[3]}`));});
 add('Reflection: '+m.reflection,12,true);if(s.reflection.text.trim())add((s.reflection.submitted?'Submitted: ':'Draft (not submitted): ')+s.reflection.text);else add('No reflection entered.');
 }
 block('Graded knowledge check');if(!state.exam.attempts.length)add('No submitted attempts.');state.exam.attempts.forEach((at,j)=>{block(`Attempt ${j+1}: ${at.percent}% (${at.score}/20)`);add(new Date(at.date).toLocaleString());C.exam.forEach((q,i)=>add(`${i+1}. ${q[0]} Answer: ${q[1][at.answers[i]]}. ${at.answers[i]===q[2]?'Correct.':'Correct answer: '+q[1][q[2]]+'.'} ${q[3]}`));});if(!state.exam.submitted){block('Current assessment draft');C.exam.forEach((q,i)=>add(`${i+1}. ${q[0]} Answer: ${q[1][state.exam.answers[i]]||'unanswered'}`));}
 flushPage();doc.save('healthcare-billing-foundations-my-answers.pdf');setFeedback('pdf','Your PDF download is ready.');}
 catch(e){setFeedback('pdf',e.message||'The PDF could not be created. Please try again.',true);}finally{if(state.route==='certificate')render();}}
 // One focused document counts time. A 1s heartbeat never credits sleep/large gaps.
 let lastTick=performance.now(),lastActivity=performance.now(),wasActive=document.visibilityState==='visible'&&document.hasFocus();
 function active(now){return document.visibilityState==='visible'&&document.hasFocus()&&now-lastActivity<90000;}
 function tick(){const now=performance.now(),delta=now-lastTick,isActive=active(now);if(wasActive&&isActive&&delta>0&&delta<=2500){try{const current=storageOK?Math.max(elapsed,Number(localStorage.getItem(TIME_KEY))||0):elapsed;elapsed=current+delta/1000;if(storageOK)localStorage.setItem(TIME_KEY,String(elapsed));}catch(e){storageOK=false;warn('Time and progress cannot be saved by this browser. Export your work before leaving.');}}lastTick=now;wasActive=isActive;$('#clock').textContent=duration(elapsed,true);$('#clock').title=isActive?'Counting active learning time':'Paused while hidden, unfocused or idle';}
 ['pointerdown','keydown','scroll','touchstart','input'].forEach(type=>document.addEventListener(type,()=>{lastActivity=performance.now();},{passive:true,capture:true}));
 window.addEventListener('focus',()=>{lastTick=performance.now();lastActivity=lastTick;wasActive=true;});window.addEventListener('blur',()=>{tick();wasActive=false;});document.addEventListener('visibilitychange',()=>{tick();lastTick=performance.now();wasActive=false;});window.addEventListener('pagehide',()=>{tick();save();});setInterval(tick,1000);
 window.addEventListener('resize',()=>{applyPanel();drawLines();});
 window.addEventListener('storage',ev=>{if(ev.key===TIME_KEY){elapsed=Math.max(elapsed,Number(ev.newValue)||0);}if(ev.key===KEY&&ev.newValue){try{const remote=JSON.parse(ev.newValue);if(remote.version===1){const route=state.route,collapsed=state.collapsed;state=remote;state.route=route;state.collapsed=collapsed;C.modules.forEach(m=>{ms(m.id);as(m);});render();}}catch(e){/* Keep the current valid session if a different tab writes invalid data. */}}});
 save();render();tick();
})();
