'use strict';
window.COURSE = {
 title:'Foundation to US Healthcare', version:1, pass:80,
 sources:[
 ['HIPAA: minimum necessary','https://www.hhs.gov/hipaa/for-professionals/privacy/guidance/minimum-necessary-requirement/index.html'],
 ['CMS: professional claim forms','https://www.cms.gov/medicare/coding-billing/electronic-billing/professional-paper-claim-form'],
 ['CMS: institutional claim forms','https://www.cms.gov/Outreach-and-Education/MLN/WBT/MLN7388180-MLN-WBT-1450/1450/lesson02/06/index.html'],
 ['HealthCare.gov: insurance glossary','https://www.healthcare.gov/glossary/'],
 ['Medicare: parts of Medicare','https://www.medicare.gov/basics/get-started-with-medicare/medicare-basics/parts-of-medicare'],
 ['Medicaid: managed care','https://www.medicaid.gov/medicaid/managed-care'],
 ['TRICARE: health plan options','https://www.tricare.mil/Plans/HealthPlans'],
 ['VA: community care referrals','https://www.va.gov/resources/how-to-get-community-care-referrals-and-schedule-appointments/'],
 ['IRS: HSAs and health FSAs','https://www.irs.gov/publications/p969']
 ],
 modules:[
 {id:'privacy',title:'Protecting Patient Information',short:'HIPAA Refresher',time:6,kicker:'A Responsibility At Every Step',objective:'Recognize appropriate access and protect information while working with claims.',intro:'Every claim begins with a person. Protecting their information is part of your work, even when you never speak with the patient.',sections:[
 ['HIPAA in your daily work','The Health Insurance Portability and Accountability Act protects certain individually identifiable health information held by covered entities and their business associates. In billing, protected health information (PHI) can include names, member IDs, diagnoses, dates of service and payment details linked to a person.'],
 ['Use only what the task requires','For payment-related work, follow your organization’s minimum-necessary policies: access, request and share only the information reasonably needed. The rule has exceptions, including disclosures to providers for treatment; it is not a blanket restriction on clinical care.'],
 ['A practical pause before opening an account','Confirm your work purpose and authority. Use approved systems, verify the recipient, lock an unattended workstation and keep passwords private. Report a suspected disclosure through your organization’s process. Curiosity is never a work purpose.']
 ],activity:{type:'sort',title:'Appropriate or not?',prompt:'Place each action in a bucket. Drag a card, or select it and choose a bucket.',buckets:['Appropriate','Not appropriate'],items:[['Open an assigned account to research its claim',0],['Look up a celebrity’s record out of curiosity',1],['Verify necessary identifiers through an approved payer channel',0],['Send a claim screenshot through personal messaging',1]],coaching:'Authorized access has a specific work purpose. Verify the recipient and use approved channels; having system access does not mean every record is yours to open.'},cfu:[
 ['You recognize a neighbor’s name in the work queue, but their account is not assigned to you. What should you do?',['Open it briefly','Access it only if your assigned work requires it','Ask a friend to open it'],1,'Recognition does not establish a legitimate work purpose.'],
 ['Which example may be PHI in a billing system?',['A public hospital address','An empty claim template','A diagnosis linked to a patient’s member ID'],2,'Health information linked to an identifiable person may be PHI.']
 ],reflection:'What habit will help you protect patient information during billing work?'},
 {id:'relationship',title:'Patients, Providers & Payers',short:'The Core Relationship',time:6,kicker:'Care → Claim → Payment',objective:'Explain the roles of the patient, provider and payer, and how a claim connects them.',intro:'A patient needs care. A provider delivers it. A payer evaluates coverage and payment. The claim brings their information together.',sections:[
 ['Follow one healthcare journey','Maria visits a cardiologist for an outpatient consultation. Maria receives the service, the cardiologist delivers it, and her health plan evaluates the claim under her coverage. This fictional example will follow us through the course.'],
 ['What a claim communicates','A claim identifies who received care, who provided it, what was done, why it was done, when it happened and which payer is asked to reimburse it. The medical record supports the service; the insurance card identifies coverage information. Neither replaces the claim.'],
 ['Two financial relationships','A payer may pay the provider for eligible services. The patient may owe a deductible, copay or coinsurance, depending on the plan and adjudication. Coverage does not mean every billed dollar will be paid.']
 ],activity:{type:'flip',title:'Meet the three participants',prompt:'Open every card to explore each independent role.',items:[['Patient','Maria receives the consultation. She may also owe part of the allowed cost.'],['Provider','The cardiologist or provider organization delivers care and submits billing information.'],['Payer','The health plan applies coverage and payment rules to the claim.']],coaching:'The patient receives care, the provider delivers care, and the payer evaluates coverage and reimbursement. The claim is the financial communication connecting them.'},cfu:[
 ['What connects service details to a request for reimbursement?',['The claim','The appointment reminder','The insurance card alone'],0,'The claim combines patient, provider, service and payer information.'],
 ['In Maria’s visit, who evaluates the claim against insurance coverage?',['Maria’s employer in every case','The cardiologist’s receptionist','The payer'],2,'The payer evaluates the claim; a provider does not unilaterally decide the plan’s payment.']
 ],reflection:'In your own words, how does a claim connect the three participants?'},
 {id:'patient',title:'Understanding The Patient',short:'Patient Fundamentals',time:10,kicker:'One Person, Several Roles',objective:'Distinguish patient and insurance roles, encounter terms and patient cost sharing.',intro:'Patient, subscriber and guarantor describe different roles. Do not assume they identify the same person.',sections:[
 ['Who is who?','Maria receives care under her husband Daniel’s employer plan. Maria is the patient and a covered dependent; Daniel is the subscriber. Both can be plan members. The guarantor is the person responsible for the account under its arrangement—we cannot infer that person from the insurance card.'],
 ['Before the encounter','Scheduling reserves the appointment. Registration confirms demographics and insurance information, such as member ID, group number and subscriber. An MRN identifies a medical record; an account number tracks an account or encounter, depending on the organization. Eligibility checks active coverage for the date of service. Benefits describe covered services and cost-sharing conditions.'],
 ['Care and dates','An encounter is an interaction in which care is delivered. Date of Service (DOS) is when the service occurs. Inpatient status requires a formal inpatient admission; outpatient care has no inpatient admission. An overnight stay alone does not prove inpatient status. Admission and discharge dates describe the start and end of a hospital stay; statement dates describe a billing period.'],
 ['What the patient may owe','A premium maintains insurance coverage. A deductible is an amount paid toward applicable covered services before certain benefits pay. A copay is a fixed amount; coinsurance is a percentage of the allowed cost. The out-of-pocket maximum limits applicable covered, in-network cost sharing for the plan year; premiums and noncovered services generally do not count. Always use the actual plan rules.'],
 ['A simple coinsurance example','Assume the deductible has been met, there is no copay, and a covered service has a $1,000 allowed amount with 20% coinsurance. The patient share is $200 and the plan share is $800. This example does not use the provider’s billed charge to calculate coinsurance.']
 ],activity:{type:'match',title:'Give Each Role Its Meaning',prompt:'Select a term, then its unique definition. Each definition is used once.',pairs:[['Patient','Receives the healthcare service'],['Subscriber','Holds the insurance policy'],['Guarantor','Is financially responsible under the account arrangement'],['Dependent','Receives coverage through another person’s policy']],explanation:'Explain why the patient, subscriber and guarantor should not automatically be treated as the same person.',coaching:'Match the role to evidence in the account. One person can have several roles, but you should never infer the guarantor from the subscriber alone.'},cfu:[
 ['Maria receives care under Daniel’s policy. Who is the subscriber?',['Maria automatically','Daniel','The hospital'],1,'Daniel holds the policy. The patient and subscriber can be different people.'],
 ['With a $1,000 allowed amount, deductible met, no copay and 20% coinsurance, what is the patient share?',['$20','$800','$200'],2,'20% × $1,000 = $200. Billed charges are not the basis in this example.']
 ],reflection:'Which patient or insurance role will you make a point of verifying rather than assuming?'},
 {id:'providers',title:'Understanding Providers',short:'Provider Roles & Services',time:9,kicker:'Who Delivered Which Service?',objective:'Identify provider types, specialties, claim roles and identifiers.',intro:'A provider can be an individual professional or an organization. The role on a claim tells you how that provider relates to the service.',sections:[
 ['People and organizations','Physicians, nurse practitioners and physician assistants provide services within applicable practice rules. Physician groups and clinics organize outpatient care. Hospitals deliver inpatient and outpatient services. Ambulatory surgery centers provide eligible same-day procedures.'],
 ['Specialties put the service in context','Primary care and family medicine provide routine and preventive care; internal medicine focuses on adults and pediatrics on children. Cardiology concerns the heart; orthopedics, bones and joints; neurology, the nervous system; oncology, cancer; gastroenterology, digestion; dermatology, skin. Radiology involves imaging, anesthesiology involves anesthesia and perioperative care, and emergency medicine involves urgent evaluation and treatment.'],
 ['Roles change with the encounter','The primary care provider (PCP) is often the first contact. A referring provider directs the patient to another provider; an ordering provider requests a test or service. A rendering provider performs the service. The billing provider submits the claim. An attending provider is primarily responsible for care during relevant facility services. A specialist can also be the rendering provider.'],
 ['Identifiers and service types','The National Provider Identifier (NPI) is a 10-digit identifier for covered healthcare providers; it is not a tax number or a guarantee of payer enrollment. A Taxpayer Identification Number (TIN) identifies the taxpayer. Services may be evaluation and management, diagnostic tests, therapeutic treatment, surgery or facility services.']
 ],activity:{type:'match',title:'Read the provider’s role',prompt:'Connect each claim role to its unique function.',pairs:[['Rendering provider','Performs the billed healthcare service'],['Billing provider','Submits the claim for reimbursement'],['Referring provider','Directs the patient to another provider'],['Ordering provider','Requests a laboratory test or imaging service'],['Attending provider','Has primary responsibility for the facility patient’s care']],coaching:'Provider role and specialty answer different questions. A cardiologist may render a service while a physician group is the billing provider; verify both roles and their identifiers.'},cfu:[
 ['A PCP sends Maria to a cardiologist. In that referral, the PCP is the…',['Referring provider','Payer','Facility billing entity'],0,'The PCP initiates the referral; the cardiologist is the specialist.'],
 ['Which statement is correct?',['An NPI and a TIN mean the same thing','An NPI guarantees coverage','An NPI identifies a provider; a TIN identifies a taxpayer'],2,'These identifiers serve different purposes.']
 ],reflection:'Why might a claim’s rendering provider and billing provider be different?'},
 {id:'payers',title:'Understanding Payers',short:'Coverage & Payer Fundamentals',time:15,kicker:'Identify The Program, Plan And Network',objective:'Distinguish major US coverage programs, common managed-care plan structures, funding accounts and the checks that determine payer responsibility.',intro:'A payer evaluates claims according to a specific program and plan. Identify the coverage family, plan structure, network rules and order of benefits before drawing conclusions from the name on a card.',sections:[
 ['The Coverage Landscape','US healthcare coverage includes federal programs, joint federal-state programs and private plans. Medicare, Medicaid, Medicare Advantage, employer-sponsored coverage, individual commercial coverage, TRICARE, CHAMPVA and VA healthcare follow different eligibility and billing rules. Begin by identifying the exact program and plan rather than treating every card as standard commercial insurance.'],
 ['Map The Parts Of Medicare','Original Medicare includes Part A and Part B. Part A helps cover inpatient hospital, skilled nursing facility, hospice and certain home health care; Part B helps cover physician and other provider services, outpatient care, durable medical equipment and preventive services. Medicare Advantage, also called Part C, is an alternative delivered through a Medicare-approved private plan and commonly uses plan networks. Part D covers prescription drugs. Medigap supplements Original Medicare cost sharing and is different from Medicare Advantage.'],
 ['Recognize Medicaid Delivery Models','Medicaid is jointly funded by federal and state governments, and eligibility, benefits and billing rules vary by state. A state may pay providers through fee-for-service Medicaid or arrange delivery through contracted managed care organizations. For managed Medicaid, verify the member’s assigned MCO, effective dates, network and authorization rules; a state Medicaid ID alone may not identify the entity that should receive the claim.'],
 ['Military And Veteran Programs','TRICARE is the uniformed services healthcare program, with plan options that vary by beneficiary category and location. CHAMPVA may cover certain spouses, dependents, survivors and caregivers who meet VA criteria and are not eligible for TRICARE. VA healthcare is a separate system; eligible Veterans using community care generally need a VA referral and authorization. Verify the program, eligibility source, approved provider, service and dates.'],
 ['Plan Structure Changes Access','Managed-care labels describe common network patterns, but the actual plan document controls. HMOs often organize care through a primary care provider and may require specialist referrals. PPOs generally allow out-of-network care at higher member cost. EPOs generally cover services only in network except emergencies. POS plans combine network incentives with a primary-care referral structure. Never infer coverage from the acronym alone; verify network status, referral and authorization requirements for the service.'],
 ['Eligibility, Benefits, Referrals And Authorization','Eligibility confirms active enrollment for a date of service. Benefits describe covered services, exclusions and cost sharing. A referral directs care and may satisfy a plan access rule. Prior authorization is payer approval required for some services. These checks answer different questions, and none alone guarantees claim payment.'],
 ['Payer Order And Other Payment Sources','Coordination of Benefits determines whether coverage is primary, secondary or tertiary. Workers’ compensation or automobile liability coverage may be responsible for care related to a work injury or accident, so verify the event and applicable billing rules. HSAs and health FSAs are funding arrangements used to pay or reimburse qualified medical expenses; they do not adjudicate a health insurance claim and should not be treated as insurance payers.'],
 ['Allowed Amount And Patient Responsibility','The allowed amount is the maximum amount a payer recognizes for a covered service under its fee schedule or provider contract. It can differ from the billed charge. For a contracted provider, the difference is commonly a contractual adjustment rather than patient responsibility. Adjudication identifies payment, adjustments and the patient portion. Review the actual remittance and plan rules before describing a balance.']
 ],activity:{type:'simulation',revision:2,title:'Practice A Coverage Conversation',prompt:'Maria asks, “My insurance is active. Does that mean this visit is fully paid?” Choose a response, review the feedback, and continue.',steps:[
 {question:'How do you respond first?',options:['Yes. Active coverage means everything is paid.','Active coverage is one check. We also need the service benefits and plan requirements.'],correct:1,wrong:'Eligibility confirms active coverage, not full payment. Avoid promising a dollar amount before the other checks.',right:'You separated eligibility from benefits. Maria now asks whether approval is needed.'},
 {question:'The plan requires prior authorization. What do you explain?',options:['We need the required authorization, but it does not guarantee claim payment.','An authorization replaces all other checks.'],correct:0,wrong:'An authorization does not replace coverage, coding or other payment requirements.',right:'You explained the condition without guaranteeing reimbursement. Maria mentions a second plan.'},
 {question:'How should the two plans be billed?',options:['Send both as primary and see which pays.','Let Maria choose which is primary.','Verify coordination-of-benefits rules and payer order.'],correct:2,wrong:'Payer order follows COB rules, not preference or simultaneous primary billing.',right:'You have a sound next step: verify payer order and document the coverage information.'},
 {question:'Maria’s plan is an EPO and the requested provider appears out of network. What is the best next step?',options:['Promise out-of-network coverage because the plan is active.','Verify the provider network and the plan’s emergency or exception rules before describing coverage.','Treat the EPO exactly like every PPO.'],correct:1,wrong:'An EPO generally limits coverage to its network except emergencies, but the actual plan terms and any applicable exception must be checked.',right:'You used the plan structure as a prompt to verify the actual network and coverage rules.'},
 {question:'Maria asks whether her HSA should be billed as another insurance payer. How do you respond?',options:['Yes. An HSA adjudicates the claim after the health plan.','No. An HSA is a funding account that may be used for qualified medical expenses; it is not another health insurer.'],correct:1,wrong:'An HSA holds funds for eligible expenses. It does not apply insurance benefits or adjudicate the claim.',right:'You separated the insurance payer from the account Maria may use for eligible out-of-pocket costs.'}
 ],explanation:'Explain how the program, plan structure, eligibility, benefits, network, referral and prior authorization answer different coverage questions.',coaching:'Identify the exact program and plan, then separate eligibility, benefits, network, referral, authorization and payer order. Treat HSAs and FSAs as funding arrangements rather than insurance payers. Clear explanations state what has been verified and what still determines payment.'},cfu:[
 ['Which describes managed Medicaid?',['Only employer-funded private coverage','Medicaid benefits delivered through contracted managed care organizations','A Medicare supplement'],1,'Managed Medicaid is a Medicaid delivery arrangement, not Medicare Advantage.'],
 ['What determines which of multiple plans processes first?',['Coordination of Benefits','The larger premium','The patient’s preferred insurer'],0,'COB rules establish primary, secondary and sometimes tertiary payer order.']
 ],reflection:'Write one sentence explaining why authorization does not guarantee payment.'},
 {id:'lifecycle',title:'The Claim Life Cycle',short:'From Service To Payment',time:9,kicker:'Six Stages, One Connected Story',objective:'Order the simplified claim stages and distinguish rejection, denial, reporting and payment.',intro:'Use these six stages as your foundation. Actual workflows can loop back for corrections, and reporting and payment timing can overlap.',sections:[
 ['Service Delivered → Claim Generation','The provider delivers and documents care. Charge capture records all supported billable services, supplies and procedures. Coding then helps translate that documentation into claim data. Each service line carries related details such as a code, date, units and charge. A claim should reflect the health record.'],
 ['Claim Submission → Claim Adjudication','A claim scrubber can check for missing data and common errors before submission. A clearinghouse may validate format, translate the electronic transaction and route it to the payer. A clean claim has the information needed to process without avoidable delay. A rejected claim is not accepted into adjudication; a denied claim was accepted, processed and refused for payment in whole or in part.'],
 ['Claim Reporting → Claim Payment','The payer reports the adjudication outcome. An Explanation of Benefits (EOB) explains billed, allowed, paid and patient-responsibility amounts. An Electronic Remittance Advice (ERA / 835) sends structured payment and adjustment information to the provider. Claim Adjustment Reason Codes (CARCs) explain financial adjustments; Remittance Advice Remark Codes (RARCs) add detail. An ERA reports the result; it does not itself transfer funds.'],
 ['A claim can take another pass','A rejected claim may need correction before adjudication. A denial may need review and a permitted next action. At this foundation stage, recognize the distinction and where the response belongs; detailed follow-up strategy comes in separate training.']
 ],activity:{type:'sequence',title:'Build The Claim Life Cycle',prompt:'Move the six unique stages into the simplified course sequence. Use the up and down controls.',items:['Service Delivered','Claim Generation','Claim Submission','Claim Adjudication','Claim Reporting','Claim Payment'],explanation:'Explain the difference between a rejected claim and a denied claim.',coaching:'The sequence is Service Delivered → Claim Generation → Claim Submission → Claim Adjudication → Claim Reporting → Claim Payment. Submission does not prove acceptance; reporting explains an outcome and is distinct from receiving funds.'},cfu:[
 ['A clearinghouse stops a claim for an invalid member ID before adjudication. This is a…',['Payment','Denial after coverage review','Rejection'],2,'A front-end rejection prevents the claim from entering normal adjudication.'],
 ['What does an ERA communicate?',['Remittance and adjustment information','Only the appointment date','A guarantee that every claim was paid in full'],0,'An ERA explains adjudication results and is distinct from the funds transfer.']
 ],reflection:'What would you check before saying a submitted claim has been adjudicated?'},
 {id:'billing',title:'One Encounter, Two Billing Perspectives',short:'Introducing PB & HB',time:6,kicker:'Professional Care And Facility Resources',objective:'Explain why a single encounter can generate professional and institutional claims.',intro:'Maria has an outpatient procedure in a hospital. The professional service and the facility resources may be represented by separate claims.',sections:[
 ['Professional billing','Physician Billing (PB), also called professional billing, generally represents services supplied by individual healthcare professionals. The professional paper form is CMS-1500 and the electronic transaction is 837P. The professional may work in an office or in a hospital.'],
 ['Hospital billing','Hospital Billing (HB), also called institutional or facility billing in this course, generally represents the facility’s services and resources. The paper form is UB-04 (CMS-1450) and the electronic transaction is 837I. Institutional billing is not limited to inpatient stays.'],
 ['Why two claims can be appropriate','A surgeon’s work and a hospital’s operating room resources represent different components. Separate claims are not automatically duplicates. Verify the billing entity and the service represented. Billing arrangements vary, so the service location alone is not enough to classify a claim.']
 ],activity:{type:'flip',title:'Explore the two perspectives',prompt:'Open both cards to compare the components of one fictional encounter.',items:[['The professional component','The surgeon’s professional work may be billed on a CMS-1500 / 837P by the professional or group.'],['The facility component','Hospital space, supplies, nursing and other facility resources may be billed on a UB-04 / 837I.']],coaching:'Start with who is billing and what service or resource is represented. A professional service performed inside a hospital can still be a professional claim.'},cfu:[
 ['A professional claim for a hospital-based physician is generally associated with…',['837I only because of the location','837P','A patient premium invoice'],1,'Claim type follows the billing perspective, not simply the building.'],
 ['Two claims arise from one surgery. What is the best foundation-level interpretation?',['Both must be duplicates','Only one can be valid','They may represent separate professional and facility components'],2,'Review the billing entity and component before treating the claims as duplicates.']
 ],reflection:'How would you explain two billing perspectives to a new colleague?'},
 {id:'pb',title:'Physician Billing Fundamentals',short:'CMS-1500 & 837P',time:8,kicker:'Read The Professional Service',objective:'Recognize the main information groups on a professional claim.',intro:'Read a professional claim as a structured description of the patient, insurance, provider and services.',sections:[
 ['Patient, insured and provider','Confirm patient identity and the insured’s information. Identify the rendering provider, billing provider and referring or ordering provider where required. Names and identifiers serve different roles on the claim.'],
 ['Why and what','A diagnosis code explains the condition or reason associated with the service. ICD-10-CM is used for diagnoses in current workflows. CPT and HCPCS identify procedures, services or supplies. A modifier provides additional detail about a service; it is not a substitute for the underlying procedure code. A diagnosis pointer links a service line to a listed diagnosis.'],
 ['Where, when and how much','Place of Service (POS) describes the service setting, such as office, inpatient hospital or outpatient hospital. DOS identifies the service date. Units represent a reported quantity. Line charges and total charges are billed amounts, not guaranteed payment amounts.'],
 ['Your supplied training form','The provided CMS-1500 is labeled 08/05. We use its first page for locating fields only. It has four diagnosis positions and some labels that differ from the current 02/12 form. Do not use this legacy blank as a current submission template. Electronic 837P data is structured differently from a paper page.']
 ],activity:{type:'flip',title:'Read a professional claim in layers',prompt:'Open each layer before moving to the field navigation lab.',items:[['Who?','Patient and insured information; rendering, billing and referring providers.'],['Why?','Diagnosis information and pointers linking the service to the diagnosis.'],['What, where and when?','CPT/HCPCS, modifiers, Place of Service and Dates of Service.'],['How much?','Units and charges. Payment depends on adjudication, not the billed amount alone.']],coaching:'Read the service line as a whole. Procedure, modifier, diagnosis pointer, setting, dates, units and charge describe related aspects of the same billed service.'},cfu:[
 ['What does a diagnosis pointer do?',['Links a service line to a listed diagnosis','Identifies the insurer’s bank','Replaces the procedure code'],0,'A pointer relates the line to diagnosis information elsewhere on the claim.'],
 ['Which item describes where the professional service occurred?',['Type of Bill','Place of Service','Group number'],1,'POS describes the professional service setting.']
 ],reflection:'Which service-line fields help you understand what happened during the encounter?'},
 {id:'hb',title:'Hospital Billing Fundamentals',short:'UB-04 & 837I',time:9,kicker:'Read The Facility Encounter',objective:'Recognize institutional claim dates, codes, provider roles and service lines.',intro:'Institutional claims add facility-specific information that helps describe an inpatient stay or outpatient service.',sections:[
 ['The encounter and billing period','Confirm the patient, facility and payer. Statement From/Through dates describe the period covered by the bill; admission date describes the start of admission. Discharge status identifies the patient’s disposition at the end of the statement period. Do not assume a statement date is always the admission or discharge date.'],
 ['Type of Bill and patient status','Type of Bill combines facility type, bill classification and frequency information; the paper representation includes a leading zero. Patient status describes disposition, such as discharge or continued care. These fields help the payer interpret the institutional bill.'],
 ['Revenue And Procedure Information','Revenue codes identify service or accommodation categories, such as room and board, emergency room, laboratory, radiology, pharmacy, operating room and therapy. Many facility charge items originate in the Charge Description Master, or chargemaster, before appearing on a claim service line. HCPCS/CPT may be reported where applicable. Units and charges appear on service lines. Diagnoses use ICD-10-CM in current workflows; inpatient hospital procedures use ICD-10-PCS when applicable.'],
 ['Providers and reimbursement concepts','The attending provider has primary responsibility for relevant facility care; operating and other provider fields identify additional roles. A Diagnosis-Related Group (DRG) groups certain inpatient stays by clinical characteristics and resource use for reimbursement. It is not a universal payment method for every hospital claim, and outpatient claims are not simply assigned an inpatient DRG.'],
 ['Where discharge information lives','The supplied UB-04 shows discharge hour in field 16 and patient discharge status in field 17. It does not have a standalone box labeled “discharge date.” Use the applicable statement-through and discharge-status instructions and the encounter record together.']
 ],activity:{type:'flip',title:'Explore facility-specific terms',prompt:'Open each independent concept.',items:[['Type of Bill','Facility type, bill classification and claim frequency help describe the institutional bill.'],['Revenue code','A category of accommodation or service, not a substitute for every procedure detail.'],['Patient status','The patient’s disposition at the end of the statement period.'],['DRG','An inpatient grouping used in certain reimbursement systems; it does not apply to every hospital claim.']],coaching:'Institutional claims connect encounter-level information with line-level facility services. Read dates, Type of Bill, patient status and service lines together.'},cfu:[
 ['What does a revenue code generally identify?',['The subscriber’s employer','The professional’s tax ID','A category of facility service or accommodation'],2,'Revenue codes categorize institutional services and accommodations.'],
 ['Which statement about DRGs is accurate?',['They classify certain inpatient stays for reimbursement','Every outpatient claim requires an inpatient DRG','They replace patient identification'],0,'DRGs are a specific inpatient reimbursement concept, not a universal claim identifier.']
 ],reflection:'What information would you review together to understand a facility encounter?'},
 {id:'forms',title:'Claim Form Navigation Lab',short:'Find The Fields',time:15,kicker:'Two Forms, Page One Only',objective:'Locate patient, payer, provider and service fields on the supplied claim forms.',intro:'Open each supplied claim form in a separate tab, then use its printed boxes or form locators to answer the questions here.',sections:[
 ['How To Navigate','The CMS-1500 uses numbered boxes; the UB-04 uses Form Locators, often shortened to FL. Open the form in a new tab and keep this course tab available. Read each question, inspect the form, and choose the box or form locator where the information belongs. Your place saves after every answer.'],
 ['Read The Exact Form','The supplied CMS-1500 is the legacy 08/05 version, while the terminology bank describes the current 02/12 form. This activity follows the labels visible on the supplied first page and clearly marks it as a location exercise. For UB-04, distinguish statement dates in FL 6, admission date in FL 12, discharge hour in FL 16 and patient status in FL 17.']
 ],activity:{type:'forms',title:'Navigate The Claim Forms',explanation:'Explain how knowing the difference between a CMS-1500 box and a UB-04 form locator can improve claim review.',coaching:'Follow the labels on the actual form. Patient, insured and provider roles are distinct. A diagnosis is not a procedure, a line charge is not a payment, and statement dates do not automatically equal admission and discharge dates.'},cfu:[
 ['On the supplied CMS-1500, which is the billing provider area?',['24J','33','21'],1,'33 is billing provider information; 24J is rendering provider and 21 is diagnosis.'],
 ['On the supplied UB-04, which pair is correct?',['42 = revenue code; 50 = payer name','42 = patient name; 50 = attending provider','42 = diagnosis; 50 = discharge hour'],0,'Use the printed field numbers to orient yourself.']
 ],reflection:'Which pair of fields was easiest to confuse, and how will you distinguish them?'},
 {id:'compare',title:'PB & HB: Bring The Terms Together',short:'Shared & Distinct Terminology',time:7,kicker:'Compare Meaning, Not Just Labels',objective:'Distinguish shared claim terminology from form-specific concepts.',intro:'Professional and institutional claims share core information but organize some details differently.',sections:[
 ['A shared foundation','Both can identify patients, insured members, payers, providers, diagnoses, service dates, units and charges. Both can involve authorizations and patient responsibility. CPT/HCPCS appears in professional billing and institutional billing where applicable.'],
 ['Professional emphasis','CMS-1500 and 837P represent professional billing. Place of Service is an explicit professional-claim concept, alongside rendering-provider and service-line detail. A professional claim may represent care in a hospital.'],
 ['Institutional emphasis','UB-04 and 837I represent institutional billing. Type of Bill, revenue codes and patient discharge status describe facility context. DRGs may apply to certain inpatient reimbursement. Do not turn these associations into a rule that all claims in one category look identical.']
 ],activity:{type:'sort',title:'PB, HB Or Shared?',prompt:'Sort the terms into three fixed categories. Drag a card, or select it and choose a bucket.',buckets:['More Specific To PB','More Specific To HB','Shared By PB & HB'],items:[['CMS-1500 / 837P',0],['UB-04 / 837I',1],['Place of Service field',0],['Type of Bill',1],['Revenue codes',1],['ICD-10-CM diagnoses',2],['CPT/HCPCS where applicable',2],['Units and charges',2]],explanation:'Explain one item shared by PB and HB and one item that is more specific to either form.',coaching:'Shared information does not imply identical form layouts. CPT/HCPCS can occur in both, while revenue codes and Type of Bill are institutional concepts.'},cfu:[
 ['Which is shared by professional and institutional claims?',['Type of Bill','CMS-1500 form layout','Diagnosis information'],2,'Both describe diagnoses even though the form layouts differ.'],
 ['Which electronic transaction is institutional?',['837I','837P','835'],0,'837I is institutional, 837P is professional, and 835 is remittance information.']
 ],reflection:'Name one similarity and one difference between professional and institutional claims.'},
 {id:'rcm',title:'The Full Revenue Cycle',short:'RCM Overview',time:8,kicker:'The Capstone: Connect Every Stage',objective:'Place key activities in front-end, middle-cycle and back-end Revenue Cycle Management.',intro:'Revenue Cycle Management (RCM) connects the preparation for care, the translation of services into claims, and the resolution of payment.',sections:[
 ['Front end · prepare the patient and account','Scheduling, registration, eligibility, benefits, authorization and referrals prepare accurate information before care. An incorrect member ID at intake can create a claim problem later. The goal is accurate information and appropriate access to care.'],
 ['Middle cycle · translate care into a claim','Clinical documentation, charge capture, coding, claim generation and validation convert delivered services into accurate billable information. Missing documentation can affect the claim even when registration was correct.'],
 ['Back end · complete reimbursement','Claim submission, payer adjudication, payment posting, denial review, insurance follow-up and patient billing move the account toward resolution. Accounts Receivable (AR) management concerns outstanding amounts. Detailed AR and denial strategies are outside this foundation course.'],
 ['One connected system','This course uses a simplified grouping; organizations can place some functions differently. What happens during scheduling and intake can affect the claim. Documentation and billing affect adjudication. Adjudication determines payment and the next account action. Finding where an issue began helps teams improve the entire cycle.']
 ],activity:{type:'sort',title:'Place The Work In The Revenue Cycle',prompt:'Sort these activities using the course’s front/middle/back grouping.',buckets:['Front End','Middle Cycle','Back End'],items:[['Verify active coverage before care',0],['Register the patient',0],['Capture charges from delivered services',1],['Code the documented encounter',1],['Generate and validate the claim',1],['Submit the claim',2],['Post payer payment',2],['Review outstanding account balances',2]],explanation:'Explain how one front-end error could affect a middle-cycle or back-end activity.',coaching:'Upstream accuracy supports downstream payment. RCM is a connected process, not a collection of independent departments; a problem found at the back end can originate much earlier.'},cfu:[
 ['Where does coding documented services belong in this course’s model?',['Front end','Middle cycle','Back end'],1,'Coding translates the documented encounter into claim information.'],
 ['An incorrect member ID causes a later rejection. What does this illustrate?',['Only the payer can prevent claim problems','Registration is unrelated to claims','Front-end accuracy affects later claim processing'],2,'The point of the capstone is to connect upstream work with downstream outcomes.']
 ],reflection:'Follow one possible registration error through the cycle. Which later activity could it affect?'}
 ]
};
COURSE.forms=[
 {id:'cms',name:'CMS-1500 · Supplied 08/05 Form',image:'assets/cms1500-page1.png',official:'https://www.cms.gov/medicare/coding-billing/electronic-billing/professional-paper-claim-form',officialLabel:'CMS Professional Paper Claim Form Resource',note:'Legacy 08/05 training reference. Use it only to learn field locations; current CMS-1500 submission instructions use the 02/12 form.',fields:[
 ['2','Patient name',15.8,24.5,26,1.8],['1a','Insured ID number',60.1,22.5,27.3,2],['4','Insured name',60.1,24.5,27.3,1.8],['17','Referring provider',15.8,47.9,24.1,2],['21','Diagnosis',15.8,51.9,44.3,3.9],['24A','Dates of Service',15.8,55.9,16,3.6],['24B','Place of Service',31.8,55.9,2.9,3.6],['24D','CPT/HCPCS and modifiers',37.4,55.9,18,3.6],['24E','Diagnosis pointer',55.4,55.9,4.7,3.6],['24F','Line charges',60.1,55.9,8,3.6],['24G','Days or units',68.1,55.9,3.6,3.6],['24J','Rendering provider ID',76.3,55.9,11.1,3.6],['28','Total charge',60.1,69.5,10.1,1.9],['32','Service facility',35.5,71.4,24.6,5],['33','Billing provider',60.1,71.4,27.3,5]
 ],prompts:[['Locate the name of the person receiving care.','2'],['Locate the insured’s identification number.','1a'],['Locate the policy holder’s name.','4'],['Locate the referring provider.','17'],['Locate the diagnoses explaining why services occurred.','21'],['Locate when the service line occurred.','24A'],['Locate the professional service setting.','24B'],['Locate the procedure code and its modifier area.','24D'],['Locate the link from a service line to a diagnosis.','24E'],['Locate the charge for an individual service line.','24F'],['Locate the reported number of days or units.','24G'],['Locate the rendering provider identifier.','24J'],['Locate the total billed charge.','28'],['Locate the service facility information.','32'],['Locate the provider or organization submitting the bill.','33']]},
 {id:'ub',name:'UB-04 · Supplied CMS-1450 Form',image:'assets/ub04-page1.png',official:'https://www.cms.gov/Outreach-and-Education/MLN/WBT/MLN7388180-MLN-WBT-1450/1450/lesson02/06/index.html',officialLabel:'CMS UB-04 And 837I Resource',note:'Page one only, reproduced as supplied. The visible “asdf” in field 74 is source placeholder text, not a valid procedure code.',fields:[
 ['1','Facility information',1.8,1.7,29.4,6],['4','Type of Bill',92.3,1.7,6,3],['6','Statement From/Through',72.4,4.7,16.5,3],['8','Patient name',1.8,7.7,35,3],['12','Admission date',15.9,10.7,6.1,3],['16','Discharge hour',33.6,10.7,3.5,3],['17','Patient status',37.1,10.7,3.5,3],['42','Revenue codes',1.8,25.9,5.5,5],['44','HCPCS / rate / HIPPS',36.7,25.9,17.6,5],['45','Service date',54.3,25.9,8.2,5],['46','Service units',62.5,25.9,9.4,5],['47','Total line charges',71.9,25.9,11.2,5],['50','Payer name',1.8,62.3,27,6],['56','Billing provider NPI',80.6,62.3,17.7,2.5],['67','Diagnosis codes',1.8,80.4,84.9,3],['74','Procedure codes and dates',1.8,85,53,6],['76','Attending provider',60.8,85,37.5,3]
 ],prompts:[['Locate the facility’s identifying information.','1'],['Locate the institutional bill classification and frequency.','4'],['Locate the statement billing period.','6'],['Locate the patient’s name.','8'],['Locate the admission date.','12'],['Locate the discharge hour (not a discharge date).','16'],['Locate the patient’s disposition at the end of the period.','17'],['Locate the facility service-category codes.','42'],['Locate HCPCS when applicable to the line.','44'],['Locate the service-line date.','45'],['Locate the service units.','46'],['Locate the total charges for a service line.','47'],['Locate the payer names.','50'],['Locate the billing provider NPI.','56'],['Locate the principal and other diagnoses.','67'],['Locate inpatient procedure codes and their dates.','74'],['Locate the attending provider.','76']]}
];
COURSE.exam=[
 ['You are assigned a claim inquiry. What should guide access to patient information?',['Everything available in the record','Only information reasonably needed under your authorized work and policy','Whether you know the patient'],1,'Use authorized access and minimum-necessary policies for payment-related work.','HIPAA'],
 ['A colleague asks you to send a claim through a personal chat app. What is the best response?',['Send only the first page','Remove the diagnosis but leave all identifiers','Use an approved channel and verify the recipient'],2,'A personal channel is not made appropriate by sending less of the claim.','HIPAA'],
 ['Which description correctly connects the three participants?',['Patient receives care; provider delivers it; payer evaluates coverage and reimbursement','Patient adjudicates; provider buys coverage; payer treats','Provider and payer always mean the same organization'],0,'The three participants have different roles connected by a claim.','Relationships'],
 ['A child receives care under a parent’s policy. Which fact can be concluded?',['The child is always the guarantor','The parent is the patient','The child is the patient and the parent is the subscriber'],2,'Do not infer the guarantor; the account arrangement determines it.','Patient'],
 ['An eligible covered service has a $500 allowed amount, deductible met, no copay and 20% coinsurance. What is the patient share?',['$400','$100','$500'],1,'20% of the allowed $500 is $100 under the stated assumptions.','Patient'],
 ['A physician performs a service and the physician group submits the claim. The physician is the…',['Rendering provider','Payer','Subscriber'],0,'Rendering describes performance; billing describes submission.','Providers'],
 ['Which statement correctly separates identifiers?',['The NPI is a patient account number','NPI and TIN are interchangeable','An NPI identifies a provider; a TIN identifies a taxpayer'],2,'An NPI is not a tax ID, enrollment guarantee or patient identifier.','Providers'],
 ['Which arrangement delivers Medicare benefits through approved private plans?',['Managed Medicaid','Medicare Advantage','All employer plans'],1,'Medicare Advantage is distinct from Medicaid managed care.','Payers'],
 ['A service is authorized. What can you safely conclude?',['The authorization requirement may be met; other claim and coverage rules still apply','The payer must pay the full charge','No eligibility check is necessary'],0,'Authorization does not guarantee payment.','Payers'],
 ['A patient has two plans. What should determine payer order?',['The newest insurance card','The plan with the highest premium','Coordination-of-benefits rules'],2,'COB determines primary and subsequent processing order.','Payers'],
 ['Which stage comes immediately after Claim Submission in this course’s simplified sequence?',['Service Delivered','Claim Adjudication','Claim Generation'],1,'Submission is followed by adjudication, then reporting and payment in the simplified model.','Life cycle'],
 ['A clearinghouse returns a claim before adjudication because required data is missing. What is this?',['A rejection','A patient payment','A coverage denial after adjudication'],0,'A rejection is different from a payer’s adverse adjudication decision.','Life cycle'],
 ['Which statement about the EOB and ERA is accurate?',['Both are always patient bills','The ERA itself transfers the money','They explain claim processing; the ERA provides remittance information to the provider'],2,'Reporting explains the outcome; payment and a patient bill are separate concepts.','Life cycle'],
 ['A surgeon bills professional services performed at a hospital. Which pair generally applies?',['UB-04 / 837I','CMS-1500 / 837P','EOB / 835'],1,'Professional services can be performed in a facility and still use the professional transaction.','PB'],
 ['On the supplied CMS-1500, where are procedure codes and modifiers?',['24D','33','1a'],0,'24D contains procedure/service information and modifiers on the supplied form.','Forms'],
 ['On the supplied UB-04, field 17 describes…',['A standalone discharge date','The subscriber’s premium','Patient discharge status'],2,'Field 17 is disposition/status, not a standalone discharge-date box.','Forms'],
 ['Which pair is more specific to institutional claims?',['Member ID and diagnosis','Revenue codes and Type of Bill','Patient name and units'],1,'Revenue codes and Type of Bill help describe institutional services and context.','HB'],
 ['A hospital and a physician group bill the same encounter date. What should you recognize?',['They may bill different facility and professional components','They must be duplicate claims','Both must use CMS-1500'],0,'Review the billing entities and represented services before concluding duplication.','PB & HB'],
 ['Where does charge capture sit in this course’s RCM model?',['Front end','Middle cycle','Back end'],1,'Charge capture translates delivered services into billable information.','RCM'],
 ['A registration error leads to a rejected claim. What is the best overall lesson?',['Only back-end teams influence payment','Intake information does not affect reimbursement','Earlier revenue-cycle work affects later claim outcomes'],2,'The stages are connected; upstream quality supports downstream processing.','RCM']
];
